To find out the default app for a particular type of file

> xdg-mime query filetype Documents/test.pdf

    application/pdf

To find out the mime for the extension

> xdg-mime query default application/pdf

    okularApplication_pdf.desktop

to set default app for an mimetype

> xdg-mime default zathura.desktop application/pdf
to test if applied successfully

> xdg-open test.md



Make zathura the default pdf viewer

Ensures, for example, that xdg-open(1) will open pdf files with zathura.

First, ensure a desktop entry for zathura exists at /usr/share/applications/org.pwmt.zathura.desktop. If it does not, download the desktop entry from from the zathura repo to /usr/share/applications/org.pwmt.zathura.desktop.

Then, set zathura as default using xdg-mime(1)

$ xdg-mime default org.pwmt.zathura.desktop application/pdf



________________________________
Emacs :
To find unbalanced parenthesis
run check-parens 

* Program I Use
=Pandoc= - A universal document converter.

* Archive
The files mentioned below can be deleted without any side effects, they are only perserved as referened for future use: 
- Configuration files of =Xmodmap= and =Xbindkeys= have been archived into =.config= directory respectively.

* FIXME
** TODO .dotfiles README
:LOGBOOK:
- State "TODO"       from              [2023-10-29 dim. 22:41] \\
  Write a proper READEME as Luke Smith
:END:

** TODO Bookmark folder and files
:LOGBOOK:
- State "TODO"       from              [2023-10-29 dim. 22:38] \\
  Write a doc for bookmarked files and folders
:END:
** TODO Shell Aliases
:LOGBOOK:
- State "TODO"       from              [2023-10-29 dim. 22:39] \\
  Create aliases using the style used by https://github.com/LukeSmithxyz/voidrice/blob/master/.config/shell/aliasrc file in =/home/vts/.config/shell/aliasrc= file
:END:
