* Tmux Configuration
=Tmux= is a terminal multiplexer that runs the window in a process and not in a session, which means the process will not die even after closing the session.

The =XDG_CONFIG_HOME/tmux/tmux.conf= (or =~/.tmux.conf=) contains my custom Tmux configuration which includes custom keyboard shortcuts, status bar and plugins to load when Tmux starts.

Create a new tmux session:
#+begin_src shell
  tmux new -s <session_name>
#+end_src

List all tmux sessions:
#+begin_src shell
  tmux ls
#+end_src

Open an existing tmux session:
#+begin_src shell
  tmux attach -t <Session_name>
#+end_src

** TODO Plugins
:LOGBOOK:
- State "TODO"       from              [2023-09-06 Wed 21:02] \\
  This plugin need to be installed in order to load by Tmux.
:END:
#+begin_src
# run-shell /opt/tmux-logging/logging.tmux
set -g @plugin 'tmux-plugins/tmux-logging'
#+end_src

** Keybinding
- The default prefix key is ~Ctrl + b~ but i changed to ~Alt + a~.
- ~Prefix key + c~ Create a new window.
- ~Prefix key + <Window_ID>~ Switch between windows.
- ~Prefix key + d~ Detach/background a session.
- ~Prefix key + z~ Show only the current pane.
- ~Prefix key + s~ and enter windows ID to move the pane to corresponding window ID.
- ~Prefix key + j~ and enter windows ID to add the pane from the corresponding window ID.
- ~Alt + .~ List previously entered command argument by argument.
- ~Prefix key + space~ Switch to next layout.
- In copy mode (~Prefix key + [~):
  - ~Space~ Start selection.
  - ~H~ Move to top of screen.
  - ~M~ Move to middle of screen.
  - ~L~ Move to bottom of screen.
  - ~0~ Jump to the start of the line.
  - ~$~ Jump to the end of the line.
