#!/bin/sh

# The xinit program allows a user to manually start an Xorg display
# server. The startx script is a front-end for xinit.  ~/.xinitrc file
# is sourced when running startx and other programs which call xinit.

# ~/.xinitrc is handy to run programs depending on X and set
# environment variables on X server startup.


# Picom is a standalone compositor use here to get trasparent window
picom &

# feh is a lightweight and powerful image viewer that is used to
# manage the desktop wallpaper
feh --no-fehbg --bg-fill "$HOME/.local/share/wallpaper/2545282.jpg" &

# Run the status bar with dwm window manager and status bar can find
# here - https://github.com/BlackcatRs/blackdwm/blob/main/scripts/bar
# "$HOME/.local/bin/bar" &

# GPG depends on pinentry to provide user interaction for typing the
# passwords such as the passphrase of GPG key. In order to function
# properly, pinentry (which, on terminal, is either pinentry-tty or
# pinentry-curses) needs to know which tty it should listen for user
# interaction.

# When GPG is acting as your ssh-agent to provide git+ssh
# authentication, it will keep a reference of the first tty available
# when it started, which is not the same you will have when you connect
# to your VM. Unfortunately, gpg-agent has no way to know at runtime
# which tty you are connected to, so it will fail every time it tries to
# communicate with its startup tty. That's why you need to update the
# startup tty using that command. This behavior is shortly described on
# their docs.
# https://www.gnupg.org/documentation/manuals/gnupg/Agent-UPDATESTARTUPTTY.html

# The gpg-agent man page explains under the option --enable-ssh-support
# that the ssh agent protocol is not able to provide the name of the tty
# to the gpg-agent, so it defaults to using the original terminal it was
# started in. So we need to update gpg-agent's startuptty.
gpg-connect-agent updatestartuptty /bye &


# Run notification daemon
exec /usr/bin/dunst &


# Run window manager dwm
exec i3

