[module/mail]
type = custom/ipc
hook-0 = echo $(find "${XDG_DATA_HOME:-$HOME/.local/share}/mail" -type d -iname inbox -exec test -d {}/new \; -exec find {}/new -type f \; | wc -l 2>/dev/null)

format = <label>
format-prefix =  
format-prefix-foreground = ${colors.mauve}
# format-background = #4eb5d6

label = %output%
label-padding = 1

initial = 1